# ---------------------------------------------------------------------------- #
# dataset cfgs
# ---------------------------------------------------------------------------- #
dataset:
  common:
    NAME: ShapeNetPartNormal
    data_root: ../../data/ShapeNetPart/useddatasetxyz
    use_normal: True
    num_points: 4096
  train:
    split: train   #val
  val:
    split: val  #valtest
    presample: False  #True
  test:
    split: test  #val
    presample: False  #True

num_classes: 2
shape_classes: 1
num_points: 4096
normal_channel: True
feature_keys: pos,x,heights

datatransforms:
  train: [PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize,PointCloudJitter,ChromaticDropGPU] #[PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize,PointCloudJitter,ChromaticDropGPU] #[PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize] #[PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize,PointCloudJitter,ChromaticDropGPU] #[PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize] #[PointsToTensor, PointCloudCenterAndNormalize] #[PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize,PointCloudJitter,ChromaticDropGPU]     # [PointsToTensor, PointCloudCenterAndNormalize]  #
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  vote: [PointCloudScaling]
  kwargs:
    jitter_sigma: 0.001
    jitter_clip: 0.005
    scale: [0.8, 1.2]
    gravity_dim: 1
    angle: [0, 1.0, 0]

batch_size: 8  #8
dataloader:
  num_workers: 0

# ---------------------------------------------------------------------------- #
# Evaluation cfgs
# ---------------------------------------------------------------------------- #
num_votes: 10 
refine: True 

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #

# lr_scheduler:
lr: 0.001    # 8.0e-3   #5.0e-5      #8.0e-3    #7.0e-3   #0.001   #5.0e-4    #3.5e-4   #7.0e-3       #0.001  #5.0e-3  #0.01  #8.0e-3 and 7.0e-3 finetuning,0.001 5.0e-4 self-supervise
min_lr: null
optimizer:
  NAME: adamw
  weight_decay: 1.0e-4  # the best 

criterion_args:
  NAME: Poly1FocalLoss

# scheduler
epochs: 100
sched: multistep
decay_epochs: [210, 270]
decay_rate: 0.1
warmup_epochs: 0



sched_on_epoch: True

grad_norm_clip: 1
use_voting: False

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
print_freq: 10
val_freq: 1

# ----------------- Model related
pretrained_path: null

wandb:
  project: PointNext-ShapeNetPart


model:
  NAME: BasePartSeg
  encoder_args:
    NAME: PointNextEncoder
    blocks: [ 1, 1, 1, 1, 1 ] # 1, 1, 1, 2, 1 is better, but not the main focus of this paper
    strides: [ 1, 2, 2, 2, 2 ]
    width: 32
    in_channels: 7  # better than 4,6
    sa_layers: 3  # better than 2
    sa_use_res: True
    radius: 0.1
    radius_scaling: 2.5
    nsample: 32 # will not improve performance.
    expansion: 4
    aggr_args:
      feature_type: 'dp_fj'      #'dp_df_f'             #'dp_fj'
    reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu' # leakrelu makes training unstable.
    norm_args:
      norm: 'bn'  # ln makes training unstable
  decoder_args:
    NAME: PointNextPartDecoder
    cls_map: curvenet

  cls_args:
    NAME: SegHead       # SegHead  segment head or not
    global_feat: max,avg  # apped global feature to each point feature
    num_classes: 2
    in_channels: null
    norm_args:
    norm: 'bn'

